### ISSUE TITLE
Token IDs should not consecutive.

### ISSUE THREAD

**Issue by Aqrare** [DMTP-Protocol/DMTP-contract#4]
https://github.com/DMTProtocol/DMTP-contract/blob/9017307fd0b925a0afe548c8600986079b93b371/contracts/DMTPMarket.sol#L77

I'd prefer that we can chose token IDs that we will set.

**Comment by Aqrare** [comment]
Currently, token Ids are consecutive and we can't select the token ID we want to sell.
We would like to select tokenID when setting / minting.

**Comment by ramsey-dao-dmtp** [comment]
OK
