### ISSUE TITLE
Change variables name

### ISSUE THREAD

**Issue by Aqrare** [DMTP-Protocol/DMTP-contract#5]
https://github.com/DMTProtocol/DMTP-contract/blob/9017307fd0b925a0afe548c8600986079b93b371/contracts/DMTPMarket.sol#L143

I'd prefer `stickerId` => `tokenId`

https://github.com/DMTProtocol/DMTP-contract/blob/9017307fd0b925a0afe548c8600986079b93b371/contracts/DMTPMarket.sol#L66

`token` => `currencyToken`

**Comment by ramsey-dao-dmtp** [comment]
That OK
