### ISSUE TITLE
Add setMarket function in Sticker.sol

### ISSUE THREAD

**Issue by Aqrare** [DMTP-Protocol/DMTP-contract#6]
https://github.com/DMTProtocol/DMTP-contract/blob/9017307fd0b925a0afe548c8600986079b93b371/contracts/Sticker.sol#L12

I'd prefer we can change market contract after deploying

ex)
```
function setMarket(address _marketContract) public onlyOwner{
  _market == _marketContract;
}
```

**Comment by ramsey-dao-dmtp** [comment]
Let discuss about this , change the URI storage place
